auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1:7946

schema_config:
  configs:
    - from: static
      name: static
      static:
        labels:
          job: "ray-batch-inference"
          __path__: /var/log/*.log

storage_config:
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h